const HISTORY_LIST_DATA = 'HISTORY_LIST_DATA';
const CLEAR_HISTORY_LIST_DATA = "CLEAR_HISTORY_LIST_DATA";
const CHECK_IN_LIST_DATA = 'CHECK_IN_LIST_DATA';
const EMPLOYYEE_LIST_DATA = "EMPLOYYEE_LIST_DATA";
const PARTY_MAP__LIST_DATA = "PARTY_MAP__LIST_DATA"
const MAP_LIST_DATA = "MAP_LIST_DATA"
const NOTIFICATION_COUNTT = "NOTIFICATION_COUNTT";
const PROVIDER_SIGNAL_HISTORY_DATA = 'PROVIDER_SIGNAL_HISTORY_DATA';
const CLEAR_PROVIDER_SIGNAL_HISTORY = 'CLEAR_PROVIDER_SIGNAL_HISTORY';
const PULL_TO_REFRESH_PROVIDER_SIGNAL_HISTORY = 'PULL_TO_REFRESH_PROVIDER_SIGNAL_HISTORY';
const PAGE_LOADING_PROVIDER_SIGNAL_HISTORY = 'PAGE_LOADING_PROVIDER_SIGNAL_HISTORY';
const USER_SIGNAL_HISTORY_DATA = ' USER_SIGNAL_HISTORY_DATA';
const CLEAR_USER_SIGNAL_HISTORY = 'CLEAR_USER_SIGNAL_HISTORY';
const PULL_TO_REFRESH_USER_SIGNAL_HISTORY = 'PULL_TO_REFRESH_USER_SIGNAL_HISTORY';
const PAGE_LOADING_USER_SIGNAL_HISTORY = 'PAGE_LOADING_USER_SIGNAL_HISTORY';
const SIGNAL_LIST_DATA = 'SIGNAL_LIST_DATA';
const CLEAR_SIGNAL_LIST_DATA = 'CLEAR_CATEGORY_LIST_DATA';
const PULL_TO_REFRESH_SIGNAL_LIST_DATA = 'PULL_TO_REFRESH_GSIGNAL_LIST_DATA';
const PAGE_LOADING_SIGNAL_LIST_DATA = 'PAGE_LOADING_SIGNAL_LIST_DATA';
const SIGNAL_DETAIL_DATA = "SIGNAL_DETAIL_DATA";
const USER_SIGNAL_DETAIL_DATA = "USER_SIGNAL_DETAIL_DATA"
const VENUE_LIST_PAGE_DATA = "VENUE_LIST_PAGE_DATA"
const CLEAR_VENUE_LIST_PAGE_DATA = 'CLEAR_VENUE_LIST_PAGE_DATA';
const PULL_TO_REFRESH_VENUE_LIST_PAGE_DATA = 'PULL_TO_REFRESH_VENUE_LIST_PAGE_DATA';
const PAGE_LOADING_VENUE_LIST_PAGE_DATA = 'PAGE_LOADING_VENUE_LIST_PAGE_DATA';
const GET_NOTIFICATION_LIST = "GET_NOTIFICATION_LIST";
const PULL_TO_REFRESH_NOTIFICATION_LIST = "PULL_TO_REFRESH_NOTIFICATION_LIST";
const CLEAR_NOTIFICATION_LIST = "CLEAR_NOTIFICATION_LIST";
const PAGE_LOADING_NOTIFICATION_LIST = "PAGE_LOADING_NOTIFICATION_LIST";

export {

  MAP_LIST_DATA,
  PROVIDER_SIGNAL_HISTORY_DATA,
  CLEAR_PROVIDER_SIGNAL_HISTORY,
  PULL_TO_REFRESH_PROVIDER_SIGNAL_HISTORY,
  PAGE_LOADING_PROVIDER_SIGNAL_HISTORY,

  USER_SIGNAL_HISTORY_DATA,
  CLEAR_USER_SIGNAL_HISTORY,
  PULL_TO_REFRESH_USER_SIGNAL_HISTORY,
  PAGE_LOADING_USER_SIGNAL_HISTORY,


  VENUE_LIST_PAGE_DATA,
  CLEAR_VENUE_LIST_PAGE_DATA,
  PULL_TO_REFRESH_VENUE_LIST_PAGE_DATA,
  PAGE_LOADING_VENUE_LIST_PAGE_DATA,

  CLEAR_SIGNAL_LIST_DATA,
  SIGNAL_LIST_DATA,
  PULL_TO_REFRESH_SIGNAL_LIST_DATA,
  PAGE_LOADING_SIGNAL_LIST_DATA,
  SIGNAL_DETAIL_DATA,

  PARTY_MAP__LIST_DATA,

  HISTORY_LIST_DATA,
  EMPLOYYEE_LIST_DATA,
  CHECK_IN_LIST_DATA,

  CLEAR_HISTORY_LIST_DATA,

  USER_SIGNAL_DETAIL_DATA,

  GET_NOTIFICATION_LIST,
  PULL_TO_REFRESH_NOTIFICATION_LIST,
  CLEAR_NOTIFICATION_LIST,
  PAGE_LOADING_NOTIFICATION_LIST,



  NOTIFICATION_COUNTT,


};
