const USER_DATA_KEY = 'USER_DATA_KEY';
const NOTIFICATION_COUNTT = "NOTIFICATION_COUNTT";
const UPDATE_NOTIFICATION_COUNTT = "UPDATE_NOTIFICATION_COUNTT";
const NOTIFICATION_UPDATE = "NOTIFICATION_UPDATE";
const SELECTED_VENUE_ID = "SELECTED_VENUE_ID";

export {
  NOTIFICATION_COUNTT,
  USER_DATA_KEY,
  SELECTED_VENUE_ID,
  UPDATE_NOTIFICATION_COUNTT,
  NOTIFICATION_UPDATE, 
};
